#DATA
data_root: /research/cbim/medical/yg397/ACDC_2d
classes: 4
modality: mri


#MODEL
arch: medformer
in_chan: 1
base_chan: 32
conv_block: 'BasicBlock'
conv_num: [2,0,0,0,  0,0,2,2]
trans_num: [0,2,2,2,  2,2,0,0]
num_heads: [1,4,8,16, 8,4,1,1] 
map_size: 3
expansion: 2
fusion_depth: 2
fusion_dim: 512
fusion_heads: 16
proj_type: 'depthwise'
attn_drop: 0.
proj_drop: 0.



#TRAIN
epochs: 200
training_size: [256, 256]    # training crop size
start_epoch: 0
aux_loss: True
aux_weight: [0.5, 0.5]
num_workers: 4 # modify this if I/O or augmentation is slow
aug_device: 'cpu'

split_seed: 0 # random seed for train/test split (shuffle) before setting cross validation fold
k_fold: 5 # number of folds in cross validation

optimizer: adamw
base_lr: 0.0005   
betas: [0.9, 0.999]
weight_decay: 0.05  # weight decay of SGD optimizer
weight: [0.5, 1, 1, 1]  # weitght of each class in the loss function
rlt: 1 # relation between CE and Dice loss

scale: 0.3  # scale for data augmentation
rotate: 180 # rotation angle for data augmentation
translate: 0
gaussian_noise_std: 0.02
additive_brightness_std: 0.7
gamma_range: [0.5, 1.6]

print_freq: 5


#VALIDATION
ema: True
ema_alpha: 0.99
val_freq: 10 # evaluate every val_freq epochs

#INFERENCE
sliding_window: False


# DDP
world_size: 1
proc_idx: 0
rank: 0
port: 10000
dist_url: 'tcp://localhost:10000' # make sure the port here is the same as in port
dist_backend: "nccl"
multiprocessing_distributed: true
reproduce_seed: 2023  # use any seed you want, or use 'null' to disable deterministic behavior
